# Change these first
owner: jbowdre # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: runtimeterror
    url: https://runtimeterror.dev
  - name: omg
    url: https://jbowdre.lol
  - name: Scribbles 'n Bits'
    url: https://scribbles.jbowdre.lol
  - name: Gitea
    url: https://git.bowdre.net
  - name: smp.vpota.to
    url: smp.vpota.to
    port: 5223
    check: "tcp-ping"
  - name: smp1.vpota.to
    url: smp1.vpota.to
    port: 5223
    check: "tcp-ping"
  - name: smp2.vpota.to
    url: smp2.vpota.to
    port: 5223
    check: "tcp-ping"
  - name: Linkding
    url: $LINKDING_URL
  - name: Miniflux
    url: $MINIFLUX_URL
  - name: Cyberchef
    url: $CYBERCHEF_URL
  - name: Files
    url: $FILES_URL
  - name: Immich
    url: $IMMICH_URL
  - name: Ntfy
    url: $NTFY_URL
  - name: Snikket
    url: $SNIKKET_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.jbowdre.lol
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: '**I work hard** to meet a strict *"up most of the time"* SLA.'
  introMessage: This status page uses **real-time** data from my [GitHub repository](https://github.com/jbowdre/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
