# Change these first
owner: jbowdre # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # websites
  - name: https://runtimeterror.dev
    url: https://runtimeterror.dev
  - name: https://jbowdre.lol
    url: https://jbowdre.lol
  - name: https://scribbles.jbowdre.lol
    url: https://scribbles.jbowdre.lol
  - name: https://git.bowdre.net
    url: https://git.bowdre.net
  - name: https://links.bowdre.net
    url: https://links.bowdre.net

  # chat servers
  - name: smp.vpota.to:5223
    url: smp.vpota.to
    port: 5223
    check: "tcp-ping"
  - name: smp1.vpota.to:5223
    url: smp1.vpota.to
    port: 5223
    check: "tcp-ping"
  - name: smp2.vpota.to:5223
    url: smp2.vpota.to
    port: 5223
    check: "tcp-ping"
  - name: https://chat.vpota.to
    url: https://chat.vpota.to

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.runtimeterror.dev
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Terror
  introTitle: '**I work hard** to meet a strict *"usually operational"* SLA.'
  introMessage: This status page uses **real-time** data from my [GitHub repository](https://github.com/jbowdre/upptime).
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://runtimeterror.dev
    - title: GitHub
      href: https://github.com/$OWNER
  customHeadHtml: "<link rel=\"me\" title=\"proven.lol\" href=\"proven.lol/90a2f9\">"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
